name: test

on:
  pull_request:
    branches:
      - main

env:
  CHECKLY_ACCOUNT_NAME: ${{ secrets.E2E_CHECKLY_ACCOUNT_NAME }}
  CHECKLY_ACCOUNT_ID: ${{ secrets.E2E_CHECKLY_ACCOUNT_ID }}
  CHECKLY_API_KEY: ${{ secrets.E2E_CHECKLY_API_KEY }}

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    name: test - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: actions/setup-node@v3.7.0
      - run: npm ci
      - run: checkly test
      - run: checkly deploy
